# Generated by Django 3.1.1 on 2021-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('total_beds', models.IntegerField()),
                ('no_of_beds', models.IntegerField()),
                ('total_oxy', models.IntegerField()),
                ('no_of_oxy', models.IntegerField()),
                ('total_icu_wv', models.IntegerField()),
                ('icu_wv', models.IntegerField()),
                ('total_icu_wov', models.IntegerField()),
                ('icu_wov', models.IntegerField()),
            ],
        ),
    ]
