# Generated by Django 3.1.1 on 2021-04-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='icu_wov',
            new_name='beds_with_oxygen',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='icu_wv',
            new_name='beds_without_oxygen',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='no_of_beds',
            new_name='normal_icu',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='no_of_oxy',
            new_name='total_beds_with_oxygen',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='total_beds',
            new_name='total_beds_without_oxygen',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='total_icu_wov',
            new_name='total_icu_with_ventilator',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='total_icu_wv',
            new_name='total_normal_icu',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_oxy',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
