# Generated by Django 3.1.1 on 2021-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210421_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='icu_with_ventilator',
            field=models.IntegerField(null=True),
        ),
    ]
