# Generated by Django 3.1.1 on 2021-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_hospital_icu_with_ventilator'),
    ]

    operations = [
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('total_beds_with_oxygen', models.IntegerField()),
                ('total_beds_without_oxygen', models.IntegerField()),
                ('total_icu_with_ventilator', models.IntegerField()),
                ('total_normal_icu', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_beds_with_oxygen',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_beds_without_oxygen',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_icu_with_ventilator',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_normal_icu',
        ),
    ]
