# Generated by Django 3.1.1 on 2021-04-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210425_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='time_update',
            field=models.TimeField(null=True),
        ),
    ]
