# Generated by Django 3.1.1 on 2021-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210428_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
