# Generated by Django 3.1.1 on 2021-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_hospital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='beds_without_oxygen',
            field=models.IntegerField(null=True),
        ),
    ]
